version: 2

models:
  - name: dim_customers
    description: >
      Customer dimension table containing the latest customer attributes and aggregated metrics.
    columns:
      - name: customer_id
        description: Unique identifier for the customer
        tests:
          - unique
          - not_null
      - name: name
        description: Customer's full name
      - name: email
        description: Customer's email address
        tests:
          - not_null
      - name: state
        description: Customer's state/province location
      - name: country
        description: Customer's country location
      - name: gender
        description: Customer's gender
      - name: created_at
        description: Timestamp when the customer account was created
        tests:
          - not_null
      
      # Order metrics
      - name: total_completed_orders
        description: Count of orders that have not been refunded
      - name: total_refunded_orders
        description: Count of orders that have been refunded
      - name: total_sales
        description: Sum of revenue from non-refunded orders
        tests:
          - dbt_utils.expression_is_true:
              expression: '>= 0'
      - name: total_refunds
        description: Sum of revenue from refunded orders
        tests:
          - dbt_utils.expression_is_true:
              expression: '>= 0'
      - name: total_profit
        description: Sum of profit from non-refunded orders
      - name: total_items_purchased
        description: Total quantity of items across all orders
      - name: avg_items_per_order
        description: Average quantity of items per order
      
      # First purchase metrics
      - name: days_from_registration_to_first_purchase
        description: Days between customer registration and first order
      - name: first_purchase_value
        description: Revenue from first order
      - name: first_purchase_profit
        description: Profit from first order
      - name: first_purchase_basket_size
        description: Quantity of items in first order
      - name: is_first_purchase_refunded
        description: Flag indicating if first order was refunded (1 = refunded, 0 = not refunded)

  - name: fct_customer_monthly_cohort
    description: >
      Monthly snapshot of customer activity and performance metrics.
      Used for cohort analysis, retention tracking, and customer behavior monitoring.
    columns:
      - name: customer_id
        description: Unique identifier for the customer
        tests:
          - not_null
      - name: activity_month
        description: The month for which metrics are calculated (first day of month)
        tests:
          - not_null
      - name: cohort_month
        description: The month when the customer first joined (first day of month)
      - name: months_since_cohort
        description: Number of months between cohort_month and activity_month
      
      # Monthly activity metrics
      - name: total_orders
        description: Number of orders placed by the customer in this month
      - name: total_revenue
        description: Total revenue from the customer in this month
        tests:
          - dbt_utils.expression_is_true:
              expression: '>= 0'
      - name: total_profit
        description: Total profit from the customer's orders in this month
      - name: avg_order_value
        description: Average order value for the customer in this month
      - name: avg_basket_size
        description: Average number of items per order for the customer in this month
      
      # Activity flags
      - name: is_active
        description: Boolean flag indicating if customer made a purchase this month
      - name: was_active_last_month
        description: Boolean flag indicating if customer made a purchase in the previous month
      
      # Cumulative metrics
      - name: cumulative_orders
        description: Total number of orders placed by the customer up to and including this month
      - name: cumulative_revenue
        description: Total revenue generated by the customer up to and including this month
        tests:
          - dbt_utils.expression_is_true:
              expression: '>= 0'
      - name: cumulative_profit
        description: Total profit generated by the customer up to and including this month
      - name: cumulative_active_months
        description: Number of months the customer has been active up to and including this month
      
      # Activity metrics
      - name: total_months
        description: Total number of months since customer joined
      - name: active_months
        description: Total number of months where customer made at least one purchase

  - name: fct_monthly_kpis
    description: >
      Monthly aggregated business KPIs for executive reporting and trend analysis.
      Provides a high-level view of business performance across all customers.
    columns:
      - name: order_month
        description: The month for which KPIs are calculated (first day of month)
        tests:
          - unique
          - not_null
      - name: gross_merchandise_value
        description: Total revenue from all orders in the month (GMV), including refunded orders
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: '>= 0'
      - name: gross_merchandise_value_excluding_refunds
        description: Total revenue from all non-refunded orders in the month
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: '>= 0'
      - name: avg_basket_size
        description: Average number of items per order for the month
      - name: avg_order_value
        description: Average monetary value of orders for the month
      - name: total_active_customers
        description: Count of unique customers who placed at least 1 order in the month